USE master
GO

CREATE DATABASE Empresa_LSTP;
GO

USE Empresa_LSTP;

CREATE TABLE Products(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	Description VARCHAR(250) NOT NULL,
	Price DECIMAL(15,2) NOT NULL,
	Stock INT NOT NULL DEFAULT 0
);
